server:
  port: 4561

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
spring:
  application:
    name: HMC-CFT-Hearing-Service
  config:
    import: "optional:configtree:/mnt/secrets/"
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HMC_HEARING_MANAGEMENT_DB_HOST:localhost}:${HMC_HEARING_MANAGEMENT_DB_PORT:5055}/${HMC_HEARING_MANAGEMENT_DB_NAME:hmc-hearing-service}${HMC_HEARING_MANAGEMENT_DB_OPTIONS:}
    username: ${HMC_HEARING_MANAGEMENT_DB_USERNAME:ccd}
    password: ${HMC_HEARING_MANAGEMENT_DB_PASSWORD:ccd}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            store_data_at_delete: true
  flyway:
    out-of-order: true
    ignore-missing-migrations: true

azure:
  application-insights:
    instrumentation-key: ${hmc.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
