server:
  port: 4561

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
spring:
  application:
    name: HMC-CFT-Hearing-Service
  config:
    import: "optional:configtree:/mnt/secrets/hmc/"
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${CFT_HEARING_SERVICE_DB_HOST:localhost}:${CFT_HEARING_SERVICE_DB_PORT:5060}/${CFT_HEARING_SERVICE_DB_NAME:hmc_cft_hearing_service}${CFT_HEARING_SERVICE_DB_OPTIONS:}
    username: ${CFT_HEARING_SERVICE_DB_USERNAME:hmc}
    password: ${CFT_HEARING_SERVICE_DB_PASSWORD:hmc}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    out-of-order: true
    ignore-missing-migrations: true

azure:
  application-insights:
    instrumentation-key: ${hmc.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

jms:
  servicebus:
    internal:
      connection-string: ${HMC_QUEUE_CONNECTION_STRING}
      # should be an integer that is interpreted as seconds
      exponential-multiplier: ${HMC_QUEUE_EXPONENTIAL_MULTIPLIER:2}
      queue-name: ${HMC_QUEUE_NAME}
      max-retry-attempts: ${HMC_QUEUE_MAX_RETRIES:5}
    external:
      connection-string: ${HMC_SERVICE_BUS_CONNECTION_STRING_OUTBOUND}
      topic-name: ${HMC_SERVICE_BUS_TOPIC_OUTBOUND}

