java:
  applicationPort: 4561
  image: 'hmctspublic.azurecr.io/hmc/cft-hearing-service:latest'
  ingressHost: hmc-cft-hearing-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
  keyVaults:
    hmc:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
