java:
  applicationPort: 4561
  image: 'hmctspublic.azurecr.io/hmc/cft-hearing-service:latest'
  ingressHost: hmc-cft-hearing-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
  keyVaults:
    hmc:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: cft-hearing-service-POSTGRES-USER
          alias: CFT_HEARING_SERVICE_DB_USERNAME
        - name: cft-hearing-service-POSTGRES-PASS
          alias: CFT_HEARING_SERVICE_DB_PASSWORD
        - name: cft-hearing-service-POSTGRES-HOST
          alias: CFT_HEARING_SERVICE_DB_HOST
        - name: cft-hearing-service-POSTGRES-PORT
          alias: CFT_HEARING_SERVICE_DB_PORT
        - name: cft-hearing-service-POSTGRES-DATABASE
          alias: CFT_HEARING_SERVICE_DB_NAME
  environment:
    CFT_HEARING_SERVICE_DB_OPTIONS: "?stringtype=unspecified&gssEncMode=disable"
